[package]
name = "group"
version = "0.0.1"
authors = [ "manuel_puentes" ]
edition = "2018"

[lib]
name = "group"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
derive_more = "0"
serde = "1"

hdk3 = "0"
