[workspace]
members = [
    "zomes/group",
    # "zomes/request",
    "zomes/username",
    "zomes/contacts",
    "zomes/aggregator",
    "zomes/preference",
    "zomes/p2pmessage",
    "commons/file_types", 
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
#holo_hash = {git = "https://github.com/holochain/holochain", rev = "3675b58", package = "holo_hash"}

